data:
  doc_size: 10
  eval_file: data/dkn/final_test_with_entity.txt
  infer_file: data/dkn/final_test_with_entity.txt
  train_file: data/dkn/final_train_with_entity.txt
  wordEmb_file: data/dkn/word_embeddings_100.npy
  entityEmb_file: data/dkn/TransE_entity2vec_100.npy
  word_size: 8033
  # === begin ===
  entity_size: 3777
  # === end ===
  data_format: dkn
info:
  metrics:
  - auc
  - acc
  - f1
  - logloss
  show_step: 10
  save_epoch : 2
model:
  method : classification
  activation:
  - sigmoid
  attention_activation: relu
  attention_dropout: 0.0
  attention_layer_sizes: 100
  dim: 100

  # === begin ===
  entity_dim: 100
  entity_embedding_method: TransE
  transform: true

  # === end ===
  dropout:
  - 0.0
  filter_sizes:
  - 1
  - 2
  - 3
  layer_sizes:
  - 300
  # model_type: DKN_without_context
  model_type: dkn
  num_filters: 100
  infer_model_name : epoch_2

train:
  batch_size: 100
  embed_l1: 0.0
  embed_l2: 0.0
  epochs: 2
  init_method: uniform
  init_value: 0.1
  layer_l1: 0.0001
  layer_l2: 0.0001
  learning_rate: 0.0002
  loss: log_loss
  optimizer: adam
