#data
#data format:ffm
data:
     train_file  :  data/ripple/sample.txt
     eval_file  :  data/ripple/sample.txt
     test_file  :  data/ripple/sample.txt
     infer_file  :  data/ripple/sample.txt
     kg_file  : data/ripple/kg.txt
     user_clicks  : data/ripple/user_click.txt
     n_entity : 79125
     n_memory : 459
     n_relation : 25
     entity_limit : 10
     user_click_limit : 30
     data_format : ripple

#model
#model_type:deepFM or deepWide or dnn or ipnn or opnn or fm or lr
model:
    method : classification
    model_type : ripple
    activation : [linear]
    is_use_relation : True
    dtype : 32
    n_entity_emb : 50  # embedding size of entities (vector) and relations (2-D matrix)
    n_relation_emb : 50
    n_hops : 2  # number of hops
    item_update_mode : "map_item"  # update item mode, ["plus", "map_o",  "map_item", "map_all"]
    predict_mode : "inner_product"  # the method to compute the output final probabilities, ["MLP", "inner_product", "DCN"]
    n_DCN_layer : 2  # when user "DCN" do prediction, the layer number
    is_map_feature : False
    n_map_emb : 50  #the dimension of the feature after multiply a transformation matrix
    is_clip_norm : False  # decide if clip the grad norm
    max_grad_norm : 10  # maximum grad norm when doing clipping
    kg_ratio : 1.0  # the ratio of the kgs number of the first hop
    reg_kg : 0.1
    output_using_all_hops : True
    infer_model_name : epoch_2
#    load_model_name : ./checkpoint/epoch_1


#train
#init_method: normal,tnormal,uniform,he_normal,he_uniform,xavier_normal,xavier_uniform
train:
    init_method: xavier_uniform
    init_value : 0.01
    embed_l2 : 0.00001
    embed_l1 : 0.0000
    layer_l2 : 0.0000
    layer_l1 : 0.0000
    learning_rate : 0.001
    optimizer : adam
    epochs : 2
    batch_size : 128

#show info
#metric :'auc','logloss', 'group_auc'
info:
    show_step : 1
    save_epoch : 2
    metrics : ['auc','logloss']

